[package]
name = "cli"
version = "0.1.2"
authors = ["pangyazhi <pangyazhi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "0.4.0"
getopts = "0.2"
